import { test, expect, openKeyEditor, openMemberCreate } from './fixtures';
import { NOW } from './worker';

test.use({identity: 'member'});

test('exact key rows open locally with keyboard focus and retain independent drafts', async ({page, worker}) => {
  worker.seedSetupOverlap('member', 'Workstation');
  await page.goto('/admin?area=me&view=keys');
  const main = await page.locator('main#content').elementHandle();
  const reads = () => worker.requests.filter(request => request.method === 'GET' && request.view === 'keys').length;
  const before = reads();
  const oldTrigger = page.locator('[data-key-id="member-setup-old"] a[data-member-key-toggle]').last();
  const oldRow = page.locator('[data-member-key-row="member-setup-old"]');
  await oldTrigger.focus();
  await page.keyboard.press('Enter');
  await expect(oldRow).toBeVisible();
  await expect(oldTrigger).toHaveAttribute('aria-expanded', 'true');
  await openKeyEditor(page, 'rename');
  const oldName = oldRow.locator('form[action$="/rename"] input[name=name]');
  await oldName.fill('Unfinished old name');
  const family = oldRow.locator('a[data-member-key-toggle="member-setup-new"]');
  const newTrigger = page.locator('[data-key-id="member-setup-new"] a[data-member-key-toggle]').first();
  const newRow = page.locator('[data-member-key-row="member-setup-new"]');
  await family.focus();await page.keyboard.press('Enter');
  await expect(oldRow).toBeHidden();await expect(newRow).toBeVisible();
  await expect(newTrigger).toBeFocused();
  await newRow.locator('[data-member-key-close]').click();
  await expect(newTrigger).toBeFocused();
  await oldTrigger.click();
  await expect(oldName).toHaveValue('Unfinished old name');
  await oldRow.locator('[data-member-key-close]').click();
  await expect(oldRow).toBeHidden();
  await expect(oldTrigger).toBeFocused();
  await page.locator('[data-key-id="member-setup-new"] a[data-member-key-toggle]').last().click();
  await expect(page.locator('[data-member-key-row="member-setup-new"]')).toBeVisible();
  await expect(oldRow).toBeHidden();
  await oldTrigger.click();
  await expect(oldName).toHaveValue('Unfinished old name');
  await expect(oldName).toBeVisible();
  expect(await main!.evaluate(node => node === document.querySelector('main#content'))).toBe(true);
  expect(reads()).toBe(before);
  expect(worker.requests.every(request => request.method === 'GET')).toBe(true);
});

test('an open key row defers new lifecycle data and closing it permits a collection refresh', async ({page, worker}) => {
  await page.clock.install({time: new Date(NOW)});
  await page.goto('/admin?area=me&view=keys&key=member-key');
  const revision = await page.locator('main').getAttribute('data-console-revision');
  worker.expireKey('member-key');
  await page.locator('main#content').focus();
  worker.advanceClock(120000);
  await page.clock.fastForward(120000);
  await expect(page.locator('[data-console-status]')).toHaveText('有新数据');
  await expect(page.locator('[data-member-key-row="member-key"]')).toBeVisible();
  expect(await page.locator('main').getAttribute('data-console-revision')).toBe(revision);
  await page.locator('[data-member-key-close="member-key"]').click();
  await page.locator('main#content').focus();
  worker.advanceClock(120000);
  await page.clock.fastForward(120000);
  await expect(page.locator('[data-key-id="member-key"] [data-key-state]')).toHaveAttribute('data-key-state', 'expired');
  await expect(page.locator('[data-member-key-row]:not([hidden])')).toHaveCount(0);
  await expect(page.locator('[data-console-status]')).toBeHidden();
  expect(worker.requests.every(request => request.method === 'GET')).toBe(true);
});

test('a quiet exact-key response cannot reopen a row closed during that read', async ({page, worker}) => {
  await page.clock.install({time: new Date(NOW)});
  await page.goto('/admin?area=me&view=keys&key=member-key');
  const main = await page.locator('main#content').elementHandle();
  const revision = await page.locator('main').getAttribute('data-console-revision');
  worker.expireKey('member-key');
  const read = worker.hold({method: 'GET', path: '/admin', view: 'keys'});
  await page.locator('main#content').focus();
  worker.advanceClock(120000);
  await page.clock.fastForward(120000);
  await read.entered;
  await page.locator('[data-member-key-close="member-key"]').click();
  await page.locator('main#content').focus();
  const response = page.waitForResponse(result => new URL(result.url()).pathname === '/admin' && new URL(result.url()).searchParams.get('key') === 'member-key');
  read.release();
  await response;
  await page.clock.runFor(50);
  expect(await main!.evaluate(node => node === document.querySelector('main#content'))).toBe(true);
  expect(await page.locator('main').getAttribute('data-console-revision')).toBe(revision);
  await expect(page.locator('[data-member-key-row]:not([hidden])')).toHaveCount(0);
  worker.advanceClock(120000);
  await page.clock.fastForward(120000);
  await expect(page.locator('[data-key-id="member-key"] [data-key-state]')).toHaveAttribute('data-key-state', 'expired');
  await expect(page.locator('[data-member-key-row]:not([hidden])')).toHaveCount(0);
});

test('an unknown write result locks other mounted key forms until an authorized reread', async ({page, worker}) => {
  await page.goto('/admin?area=me&view=keys&key=member-key');
  await openMemberCreate(page);
  await page.locator('[data-member-key-create] input[name=name]').fill('Unsubmitted new key');
  await openKeyEditor(page, 'rename');
  const key = page.locator('[data-key-detail="member-key"]');
  await key.getByRole('textbox', {name: '密钥名称', exact: true}).fill('Unconfirmed rename');
  const write = worker.hold({method: 'POST', path: '/me/ui/keys/member-key/rename'});
  await key.getByRole('button', {name: '保存名称', exact: true}).click();
  await write.entered;
  write.release(503);
  await expect(page.locator('[data-member-feedback]')).toContainText('操作结果尚未确认');
  await expect(page.locator('main')).toHaveAttribute('data-member-mutation-blocked', 'true');
  await expect(page.locator('[data-member-key-create] button[type=submit]')).toBeDisabled();
  await expect(key.getByRole('button', {name: '撤销密钥', exact: true})).toBeDisabled();
  await page.getByRole('button', {name: '撤销我的全部密钥', exact: true}).click();
  await expect(page.locator('#key-bulk-actions button[type=submit]')).toBeDisabled();
  expect(worker.requests.filter(request => request.method === 'POST')).toHaveLength(1);
  const recovery = page.locator('[data-member-feedback]').getByRole('link', {name: '查看当前密钥', exact: true});
  await expect(recovery).toHaveAttribute('href', '/admin?area=me&view=keys&key=member-key');
  await recovery.click();
  await expect(page).toHaveURL('/admin?area=me&view=keys&key=member-key');
  await expect(page.locator('[data-member-key-row="member-key"]')).toBeVisible();
  await expect(page.locator('main')).not.toHaveAttribute('data-member-mutation-blocked', 'true');
  expect(worker.requests.filter(request => request.method === 'POST')).toHaveLength(1);
  await openKeyEditor(page, 'rename');
  await expect(page.locator('[data-key-detail="member-key"]').getByRole('button', {name: '保存名称', exact: true})).toBeEnabled();
});

test('a known withdrawn service owner rejection removes the old service scope without replay',async({page,worker})=>{
  const service=await worker.seedDelegatedService();
  await page.goto(`/me/service-accounts/${service}?view=keys`);
  await openMemberCreate(page);
  const form=page.locator('[data-member-key-create]');
  await form.getByRole('textbox',{name:'名称',exact:true}).fill('Rejected synthetic creation');
  await form.getByRole('checkbox',{name:'Codex',exact:true}).check();
  worker.withdrawServiceOwner(service);
  await form.getByRole('button',{name:'创建密钥',exact:true}).click();
  await expect(page.locator('[data-console-recovery]')).toBeVisible();
  expect(await page.locator('.shell,.identity,[data-service-id],[data-key-id],[data-ui-props]').count()).toBe(0);
  await expect(page.locator('[data-console-recovery]')).toContainText('刚才的操作未执行');
  expect(worker.countKeys(service)).toBe(0);
  expect(worker.requests.filter(request=>request.method==='POST')).toHaveLength(1);
});
