/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 7305cd3fd1b2240290f6a7cbae8c46c0)
interface __BaseEnv_Env {
	DB: D1Database;
	CODEX_EGRESS_BASE_URL: string;
	CODEX_OAUTH_TOKEN_URL: string;
	CODEX_CLIENT_ID: string;
	ADMIN_DASHBOARD_HOST: string;
	CONSOLE_EMAIL_DOMAIN: string;
	REQUEST_AUDIT_RETENTION_DAYS: string;
	TOKEN_ENCRYPTION_KEY_V1: string;
	API_KEY_HASH_PEPPER: string;
	ADMIN_SECRET: string;
	CODEX_EGRESS_SECRET: string;
	FEISHU_APP_ID: string;
	FEISHU_APP_SECRET: string;
	TOKEN_AUTHORITY: DurableObjectNamespace<import("./src/index").TokenAuthority>;
	CREDENTIAL_EVENTS: DurableObjectNamespace<import("./src/index").CredentialEvents>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "TokenAuthority" | "CredentialEvents";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CODEX_EGRESS_BASE_URL" | "CODEX_OAUTH_TOKEN_URL" | "CODEX_CLIENT_ID" | "ADMIN_DASHBOARD_HOST" | "CONSOLE_EMAIL_DOMAIN" | "REQUEST_AUDIT_RETENTION_DAYS" | "TOKEN_ENCRYPTION_KEY_V1" | "API_KEY_HASH_PEPPER" | "ADMIN_SECRET" | "CODEX_EGRESS_SECRET" | "FEISHU_APP_ID" | "FEISHU_APP_SECRET">> {}
}
