import { consoleAssetBytes } from "./console-asset-metrics";
import { projectDesignTokens } from "./design-tokens";
import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
const buildDirectory = mkdtempSync(join(tmpdir(), "mini-console-"));
const check = process.argv.includes("--check");
function output(path: string, contents: string): void {
  if (check) {
    if (readFileSync(path, "utf8") !== contents) throw new Error(`${path} is out of date. Run pnpm console:build.`);
  } else writeFileSync(path, contents);
}
try {
const tokens = await projectDesignTokens(readFileSync("design.md", "utf8"));
output("src/admin/generated/tokens.css", tokens.css);
output("design.md", tokens.designMd);
const outfile = join(buildDirectory, "console.js");
const built = spawnSync("node_modules/.bin/esbuild", [
  "src/admin/client/main.tsx",
  "--bundle",
  "--format=esm",
  "--minify",
  "--target=es2022",
  "--jsx=automatic",
  `--outfile=${outfile}`,
  "--define:process.env.NODE_ENV=\"production\"",
  "--legal-comments=eof"
], { stdio: "inherit" });
if (built.status !== 0) throw new Error("Console client compilation failed.");
const code = readFileSync(outfile, "utf8");
if (!code.trim()) throw new Error("Console client bundle is empty.");
output(
  "src/admin/generated/console-client.ts",
  `/** Generated by scripts/build-console-client.ts. Do not edit. */\nexport const consoleClientSource = ${JSON.stringify(code)};\n`
);
console.log("console client bytes", consoleAssetBytes(code));

const cssFile = join(buildDirectory, "console.css");
const styles = spawnSync("node_modules/.bin/tailwindcss", ["-i", "src/admin/console.css", "-o", cssFile, "--minify"], {stdio: "inherit"});
if (styles.status !== 0) throw new Error("Console style compilation failed.");
const css = readFileSync(cssFile, "utf8");
console.log("console CSS bytes", consoleAssetBytes(css));
output("src/admin/generated/console-styles.ts", `/** Generated from tokens/console.resolver.json and src/admin/console.css. Do not edit. */\nexport const consoleStyles = ${JSON.stringify(css)};\nexport const consoleTheme = ${JSON.stringify(tokens.theme)};\n`);
} finally { rmSync(buildDirectory, {recursive: true, force: true}); }
